#!/bin/sh

exec 2>&1

_HOME=/home/users/rosterbot

cd $_HOME

exec /usr/local/bin/softlimit -m 209715200 \
 /usr/local/bin/setuidgid rosterbot\
  /usr/bin/perl $_HOME/scripts/rosterbot.pl \
   --debug
